version: "3"
services:
    website:
        image: dbwebb/sechat:website
        #volumes:
            #- "view:/home/dbwebb/repo/view:r"
            #- "apache.conf:/etc/apache2/sites-available/000-default.conf:r"
        ports: [ "11042:80" ]
